{% set version = "2.4" %}

package:
    name: capturer
    version: {{ version }}

source:
    fn: capturer-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/c/capturer/capturer-{{ version }}.tar.gz
    sha256: 090142a58f3f85def3a7dd55d9024d0d1a86d1a88aaf9317c0f146244994a615

build:
    number: 0
    skip: True  # [win]
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - pip
    run:
        - python
        - humanfriendly

test:
    imports:
        - capturer

about:
    home: https://capturer.readthedocs.org
    license: MIT
    summary: 'Easily capture stdout/stderr of the current process and subprocesses.'

extra:
    recipe-maintainers:
        - ocefpaf
