travis:
  secure:
    BINSTAR_TOKEN: Mll7VitRG1fmdWwyGCg93YXpxL+X6zbzrioFDJKIzocQYqmZs0Dc7x2bQrNyeOLpElRYejmqg3vhW5DyQt0LVFPo96I3nl7SG2mOHF4tCSLoP5W6/LrHaGCBVB38m+i/d4D0Mx+AWFepDwzvkA/T2h+2H2xJqI/PfEK2URsKHzeH2xFgJ4boRTo/ZsXFMvfuiLRMg/8IldELseo8x4CS8LrtZC3alhONfAZt1xcxtpIceU9C8PS4RiNWvTFMZyOfPC3bI77YnVxjHkJnb+RJ6Z/ph28KhNxW/zcwMzqWG3+cjEMHv7xMBCsehDp+o5xUY9oKwAAu9t7TXTVNpCwGGYJdQO4Xt+beKT1lAe8oFWDGHIOd6/NkJXG6ZdbGEmtpJGIo//SFLr0Mo84H+Yuf8v1RHBgS+Nfpbr8S9z4LuXwggL86V2PZFqLmPQnGjTJEVXwhqGQ3qcja1ST4/vK0KrR7zue8Llvy6/qBhIE6ehdWPtlIiAE4sVtJSCTCk7iFa4m7ofwbg+EoWvWAqAaHzYPdPCHWDdSMNwYjAW52/0Nw3omlzGWJTn/TAaPaVzwJRnU8KUKMctPhwUDD063aKh64xVM/8olDY/iZXhgdQB0va1PgluqFi/jfJwNAlvgS8vZfunMxgnvYkjNzCJ+yqzFbsSk55dDVdBU9KBW+UtA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
