travis:
  secure:
    BINSTAR_TOKEN: DsKXPuB88wGT4mf1oJwGl5I8OO4xE2aO0kEcKZALPCJ1ey6Kua8cuACivPG/QiUEhPLnJKkJlT2eqGj0milasGqR4T2a7oYMFDx6ws9Sig0jmOw5B7ZHwpOhJfx/wi3CnLzIvVtPSrd75Fckit3mInf0fvwVCuMsCVpqpSZf0lZhVA9PLznOUHnVVcdlWLwqxINjpIU12LzXSPPsMx7/aF9uiIKK3GkivTNK6haGK+eKRbpPyc56yHK6FXJZrezH7AZdYq044WqceRA8PkcYoDLbFr0jeiD4liSLn6Xi4BDDLT9mtTPGnHr1Lp0cGZzzdeSHCBFv0jjTkK9sB6QRSxVcNCW8aoIAvlXw1MK1bcVsjTPJkq4JttzSYbudKtAUDf7pdL22B9wA0h5ygDFsbNxpHuuoe5RkmbnCGZ9iRloRtWC4xNcrlO8uZ9KL50h242ELFZIiE0T4z4vh4vK9NYRiS+4id+lhJuD0ZT3xw2klX1P/Wr9vrbXR/DhmWMZv0+PeZbg5la/26LyTJMnrZ2KyFeZbuBmVtoNIPnZZGsiuy7O/Y+X/3Nrx1cWwxUQcRuXUlydgC8xwordFYo0poGjKhuaJAkv8FmkIWXvRSzGNBWmhj7LcM66ETKP0hmAkFwjCNS4RG/g9rOP7QK1IRxeAVjqPbbT5PVIHeQeFWYo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
